#!/usr/bin/env ruby

require 'yaml'

git_ref = File.read('knative-docs-git/.git/ref').chomp
docker_image_digest = File.read('hello-world-image/digest').chomp

added_k8s_labels = <<-LABELS
      revisionTemplate:
        metadata:
          annotations:
            git-ref/knative-docs-git: #{git_ref}
            image-digest/hello-world-image: #{docker_image_digest}
LABELS
added_k8s_labels.chomp!

service_yaml = File.read('knative-docs-git/serving/samples/helloworld-ruby/service.yaml')

puts
puts 'Rewriting Knative Service YAML'
puts

service_yaml.gsub!('      revisionTemplate:', added_k8s_labels)
service_yaml.gsub!('docker.io', 'us.gcr.io')
service_yaml.gsub!('{username}', 'cf-elafros-dog')
service_yaml.gsub!('/helloworld-ruby', "/hello-world-image@#{docker_image_digest}".chomp)

puts service_yaml

File.write('deployment-yaml/service.yaml', service_yaml)

puts
puts 'Done.'
puts
