#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

DOCKER_IMAGE_DIGEST=$(cat hello-world-image/digest)

echo
echo Rewriting Knative Service YAML
echo

sed "s/docker.io\/{username}\/helloworld-ruby/us.gcr.io\/cf-elafros-dog\/hello-world-image@$DOCKER_IMAGE_DIGEST/g" \
knative-docs-git/serving/samples/helloworld-ruby/service.yaml | \
tee deployment-yaml/service.yaml

echo
echo Done.
echo
